write-host "-----Deleting user UWP Apps "
$UWPApps = @(
"Microsoft.Microsoft3DViewer"
"Microsoft.MixedReality.Portal"
"Microsoft.People"
"Microsoft.Wallet"
"Microsoft.SkypeApp"
"microsoft.windowscommunicationsapps"
"Microsoft.WindowsMaps"
"Microsoft.YourPhone"
"Microsoft.ZuneMusic"
"Microsoft.ZuneVideo"
"DellInc.PartnerPromo"
"DellInc.DellDigitalDelivery"
"Microsoft.BingTranslator"
"Microsoft.BingWeather"
"Microsoft.Advertising.Xaml"
"Microsoft.549981C3F5F10"
"AppUp.IntelOptaneMemoryandStorageManagement"
"Microsoft.Getstarted"
"Microsoft.MicrosoftOfficeHub"
"Microsoft.Xbox.TCUI"
"Microsoft.XboxApp"
"Microsoft.XboxGameOverlay"
"Microsoft.XboxGamingOverlay"
"Microsoft.XboxIdentityProvider"
"Microsoft.XboxSpeechToTextOverlay"
"A025C540.Yandex.Music"
"Microsoft.WindowsFeedbackHub"
"Microsoft.GetHelp"
"Microsoft.WindowsAlarms"
"Microsoft.MicrosoftSolitaireCollection"
"Microsoft.Print3D"
"Microsoft.PowerAutomateDesktop"
"MicrosoftWindows.Client.WebExperience"
"Microsoft.BingNews"
"Microsoft.GamingApp"
"MicrosoftTeams"
"Microsoft.Todos"
"Clipchamp.Clipchamp"
"SpotifyAB.SpotifyMusic"
"Microsoft.Windows.DevHome"
"Microsoft.OutlookForWindows"
"Microsoft.Office.OneNote"
"MicrosoftCorporationII.MicrosoftFamily"
"MirametrixInc.GlancebyMirametrix"
)
foreach ($UWPApp in $UWPApps) {
	write-host "-------------------------------------------------------------------------------------------------"
	write-host "-------------------------------------------------------------------------------------------------"
	write-host $UWPApp	
	write-host "-------------------------------------------------------------------------------------------------"
Get-AppXProvisionedPackage -Online | Where-Object DisplayName -eq $UWPApp | Remove-AppxProvisionedPackage -Online
}